### ISSUE TITLE
File names are handled as full paths if it contains some special characters

### ISSUE THREAD

**Issue by RafaelSchug** [Thanatoslayer6/spottydl#70]
Example:
https://open.spotify.com/intl-pt/track/3sslYZcFKtUvIEWN9lADgr

The file name _First Love/Late Spring.mp3_ will be read as a full path instead of a filename.

I'm not sure what would be the best approach to fix this issue, whether using regex to replace these special characters or using `encodeURIComponent` to automatically handle the string and then using `decodeURIComponent` when needed.

**Comment by Thanatoslayer6** [comment]
Good Day!

I've decided to replace special characters like `/` and `\` with whitespaces to avoid this issue. 927b2e8
